version: "3"

services:
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
