version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagbok_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./logs:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - dagbok_network

networks:
  dagbok_network:
    driver: bridge
