name: "Terraform Deploy"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Autentica no Google Cloud usando a service account
      - name: Configure GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 3) Configura o projeto e a região no gcloud (opcional, mas ajuda se for rodar gcloud)
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "dagbokj"
          install_components: kubectl

      # 4) Instala Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"  # Versão válida do Terraform

      # 5) Entra na pasta onde ficam os arquivos .tf (se estiver em "terraform/")
      - name: Enter terraform directory
        run: cd terraform
        shell: bash

      # 6) Inicializa Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # 7) Valida se a sintaxe do Terraform está OK
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # 8) Gera o plano em uma única linha
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan -input=false -var "django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}"

      # 9) Aplica o plano, se estivermos na branch main, em uma única linha
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false tfplan